[pytest]
# ===================== 核心配置 =====================
# 测试用例目录（你的用例在 testcases 文件夹）
testpaths = testcases

# 用例识别规则（不用改）
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# ===================== 自动运行参数 =====================
# 自动带Allure报告参数，不用你手动敲命令
pytest testcases/ --env=test -q

# ===================== 注册你的环境标记（必加！） =====================
# 你之前 environment.py 里的 run_mark
markers =
    test: 测试环境标记
    beta: 预发环境标记
    master: 生产环境标记
    test_run: test环境专属用例
    beta_run: beta环境专属用例
    prod_run: prod环境专属用例